### PR TITLE
Rebuild for new compilers (again)

### PR DESCRIPTION
**Pull request by CJ-Wright**
Due to an issue in ci-scripts, which has been resolved, there was a bad version
number bump in the main channel for this package.

This PR will increase the build number for the new compiler's build by 1000,
allowing them to take precedence when the new compilers are merged with the
main branch.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by CJ-Wright** [comment]
@conda-forge/libdb looks like this could use some clang help

**Comment by CJ-Wright** [comment]
@conda-forge/libdb friendly poke

**Comment by ocefpaf** [comment]
> @conda-forge/libdb looks like this could use some clang help

The only clang expert I know is @isuruf but he is busy with classes now. Oh summer vacation why are you so short...

**Comment by scopatz** [comment]
This is a known bug with the new clang: https://trac.macports.org/ticket/53577#no1  

Some patches may fix it: https://github.com/macports/macports-ports/commit/cb92cb90bdc7fb90212e928db32172546eca0f5b

**Comment by CJ-Wright** [comment]
Do we need to patch this or does this need to be patched on the anaconda side?

**Comment by scopatz** [comment]
It is this that needs the patch, just added it.

**Comment by scopatz** [comment]
looks like it worked.

**Pull request merged**
