### PR TITLE
Add Windows builds

### PR DESCRIPTION
**Pull request by shadowwalkersb**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc: @msarahan

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
@conda-forge-admin, please rerender

**Comment by shadowwalkersb** [comment]
The changes in this PR were taken from @msarahan 's commits, https://github.com/AnacondaRecipes/libdb-feedstock/commit/1da1494256e43d9056b899010e0ad24cb0680051 and https://github.com/AnacondaRecipes/libdb-feedstock/commit/7003fecb78c78a88644216bbdb0bed3021019f34.

**Comment by shadowwalkersb** [comment]
This worked on appveyor when I tested it on my fork. Should we try switching to appveyor here?

**Comment by shadowwalkersb** [comment]
Appveyor worked. This is ready for review.

**Comment by jakirkham** [comment]
Yeah if it needs `msbuild`, it needs to be on AppVeyor. There are issues with Azure and `msbuild`.

**Comment by scopatz** [comment]
Thanks!

**Comment by jakirkham** [comment]
Should add we are planning on dropping AppVeyor as a supported CI. So if this is important to you @shadowwalkersb, it would be useful to see if there is a way to get it to build on Azure.

**Comment by jakirkham** [comment]
In fact PR ( https://github.com/conda-forge/libdb-feedstock/pull/10 ) is doing exactly that 😉

**Pull request merged**
